### ISSUE TITLE
Add ability to add a article

### ISSUE THREAD

**Issue by wdoug** [codefordenver/rmfu-feed#12]
> As a general user, I want the ability to add a topic , so that I can discuss legislation and other organizational ideas.

### Acceptance Criteria:
- [x] Can create a new article when signed in
    - [x] Title field
    - [x] Content text field 
- [ ] Cannot **in any way** create an article when not signed in
- [ ] Cannot impersonate writing an article as another user
- [ ] Validates the article has a title
- [ ] Displays errors to the user

#### Not in scope
- Handling multiple requests for the same article creation (idempotency)
- Other article fields

### Tasks:
- [x] Function to persist to database
- [x] Api layer to transform request to data for persistance
- [ ] Return appropriate errors
- [x] Update UI to store article form inputs state (should this be in the global atom?)
- [x] Call the api with the correct data

**Comment by wdoug** [comment]
Just plain text initially to avoid all of the crazy security concerns of anything more complicated.

**Comment by jenshurley** [comment]
[Jen's repository of UI ideas](https://github.com/jenshurley/rmfu_ux)

**Comment by switzersc** [comment]
Template exists already

**Comment by jenshurley** [comment]
Maybe input form slides up from bottom, with list of topics still visible 
![rmfu_create_post_mock](https://cloud.githubusercontent.com/assets/7987959/11077259/66b7f6c4-87bc-11e5-8e2c-cab29a56cd09.jpeg)

**Comment by wdoug** [comment]
Blocked while we decide out how we want to handle converting mongo's `ObjectId`s to strings so the client can work with them.

**Comment by dviramontes** [comment]
I'll take up the validation piece for this. 
- no posting without a tile
- no posting without a article discription
